Basic Frontend using Svelte
metakgp/gyft pull request #115
Opened 2023-09-08 11:36 UTC by rohan-b-84

Here is the basic frontend for GYFT made using svelte :)

![Desktop View](https://github.com/metakgp/gyft/assets/82886259/5ba3dab8-5243-4e0e-a4ba-c6c24a82df29)
![Mobile View](https://github.com/metakgp/gyft/assets/82886259/c79e039e-f2e0-4705-b3ee-c2143e968ef4)

2023-09-08 12:30 UTC, chirag-ghosh requested changes
Let's also add the functionality in this PR itself.

Also, use scss instead of css.

2023-09-08 12:30 UTC, chirag-ghosh commented on frontend/README.md
> +# create-svelte
Let's replace this with a contextualised readme.

2023-09-08 12:30 UTC, chirag-ghosh commented on frontend/package-lock.json
> +{
I guess you are using npm. Wanna try yarn or pnpm? [Why?](https://dev.to/ayoub3bidi/lets-settle-things-out-2-npm-vs-yarn-vs-pnpm-5e04#:~:text=For%20NPM%20It%20is%20still,PNPM%20is%20faster%20than%20Yarn.)

2023-09-08 12:30 UTC, chirag-ghosh commented on frontend/package.json
> +	"name": "frontend",
Replace with gyft

2023-09-08 12:30 UTC, chirag-ghosh commented on frontend/src/app.html
> +<!DOCTYPE html>
Let's add metatags here.

2023-09-08 12:30 UTC, chirag-ghosh commented on frontend/src/components/Form.svelte
> +          console.log(formData);
Remove

2024-07-28 10:18 UTC, rohan-b-84 commented
not needed anymore as made one using react

2024-07-28 10:18 UTC, closed without merging