Update gyft.py
metakgp/gyft pull request #77
Opened 2022-01-28 09:32 UTC by Kunalvrm555

2022-01-28 10:12 UTC, thealphadollar commented
Hey Kunal! Thanks for the PR.

Can you please edit the description to include why this change is required?

2022-01-28 15:21 UTC, Kunalvrm555 commented
> Hey Kunal! Thanks for the PR.
> 
> Can you please edit the description to include why this change is required?

Hello Shivam
I have updated the description.
I hope it is stated well.

2022-01-29 07:04 UTC, thealphadollar commented
Hey Kunal, thanks for the description. I tried the script a few days back, and it was working. Can you please also put the error you got, and a screen showing that the error is resolved.

It'll help me review and merge the PR quickly, as compared to cloning your branch, running it, and finding the bug. 

Thank you for your patience, Kunal.

2022-01-29 07:05 UTC, thealphadollar requested changes
Please address the bug reproduction and fixture proof comment.

I'm deeply grateful for the interest and efforts you are putting in.

2022-01-29 08:44 UTC, Kunalvrm555 commented
**Error details**
TypeError : 'NoneType' object is not callable

**Steps for bug reproduction**
1. Run the script gyft.py from `metakgp : master` 
2. Input credentials when prompted 
3. The error occurs as given in description of this PR (#77) 

**Proof of fixture**

After applying changes proposed in PR and repeating the steps, the below result is achieved indicating successful execution and file named *data.txt* is generated.

![image](https://user-images.githubusercontent.com/67605729/151654333-af796f39-8d0d-428f-b776-723280789458.png)

2022-01-29 10:15 UTC, thealphadollar commented
Hey Kunal. I believe you are trying to run the script with Python2. 

It is to be used with Python3 ([ref](https://github.com/metakgp/gyft/blob/master/Pipfile)).

2022-01-29 10:52 UTC, Kunalvrm555 commented
> Hey Kunal. I believe you are trying to run the script with Python2.
> 
> It is to be used with Python3 ([ref](https://github.com/metakgp/gyft/blob/master/Pipfile)).

Hello Shivam
I doubt if that's the issue
Please look at the below screenshot
![image](https://user-images.githubusercontent.com/67605729/151658236-4052879f-6232-4321-83b5-b43fb359223b.png)

In this execution, I've used the command `py -3.9 gyft.py` to run the script which forces the interpreter to use python3
Also, I've added the following lines :
1. `import sys `
2. `print(sys.version)`

to print the version information and additional info of python used to execute the script, and the output is as highlighted in the above screenshot *(Before user input)*

2022-01-29 12:23 UTC, thealphadollar commented
Hey Kunal, thanks for sharing the error.

I tried, and the script works with Python 3.6 as specified in the Pipfile, I referenced in my previous comment.

I'd request you to edit the README.md and change the required Python version to 3.6 from 3.

2022-02-06 06:24 UTC, Kunalvrm555 commented
I have created #78 to resolve this issue. 
Please address it and close this PR.

2022-02-06 09:36 UTC, closed without merging

2022-02-06 09:36 UTC, thealphadollar commented
Thanks Kunal :D