Fixed the WORKING_DAYS period
metakgp/gyft pull request #84
Opened 2022-12-28 11:34 UTC by C-12-14

`generate_ics.py` was adding events on non-working days. This was because of the poorly defined `WORKING_DAYS` period, which included the mid-sem start and mid-sem end dates.
It was also noticed to exclude events on the first day of the semester. This was fixed by fixing the logic in the `next_weekday()` function.

2022-12-28 18:15 UTC, thealphadollar requested changes
Thanks for the PR, please address a small change I've requested.

2022-12-28 18:15 UTC, thealphadollar commented on subjects.json
> +    "CS20202": "Software Engineering",
Let's make these ALL CAPS just like other subjects.

2022-12-28 19:06 UTC, C-12-14 commented on subjects.json
> +    "CS20202": "Software Engineering",
Done!

2022-12-29 02:02 UTC, thealphadollar approved these changes

2022-12-29 02:03 UTC, merged